name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
      - feature/gh-pages

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Build
      run: yarn build
    - name: Export
      run: yarn export
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: packages/frontend/out
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
